name: CI Pipeline

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    - name: Run basic test
      run: |
        python -c "print('App builds successfully')"

    - name: Build Docker image
      run: |
        docker build -t ci-cd-app .

    - name: Run container
      run: docker run -d -p 8000:8000 ci-cd-app
